name:                advent-of-code-2k21
version:             0.0.0.0
github:              "getkey/advent-of-code-2k21"
license:             MPL-2.0
author:              "Julien Mourer"
maintainer:          "getkey@getkey.eu"
copyright:           "2021 Julien Mourer"

extra-source-files:
- readme.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/getkey/advent-of-code-2k21#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  advent-of-code-2k21-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-2k21

tests:
  advent-of-code-2k21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-2k21
